[package]
name = "newegg"
version = "0.1.0"
authors = ["fluxxu <fluxxu@gmail.com>"]
description = "Newegg Marketplace API client."
license = "MIT"
repository = "https://github.com/Ventmere/newegg"

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
chrono-tz = "0.4"
reqwest = "0.8.2"
error-chain = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"